# Generated by Django 4.1 on 2022-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(upload_to="user/images/"),
        ),
    ]
