# Generated by Django 4.1 on 2022-09-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(upload_to="static/user/images/"),
        ),
    ]
