# Generated by Django 4.1 on 2022-10-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(upload_to="user/images/"),
        ),
    ]
